# Generated by Django 4.2.7 on 2023-11-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('question_number', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField()),
                ('hr_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('min_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('question', models.CharField(max_length=600)),
                ('extra_desc', models.TextField(blank=True, max_length=600, null=True)),
                ('option1', models.TextField(blank=True, max_length=200, null=True)),
                ('option2', models.TextField(blank=True, max_length=200, null=True)),
                ('option3', models.TextField(blank=True, max_length=200, null=True)),
                ('option4', models.TextField(blank=True, max_length=200, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], max_length=200)),
                ('category', models.CharField(choices=[('0', 'obj'), ('1', 'practical')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('marks', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time_date', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course')),
            ],
        ),
    ]
