# Generated by Django 4.2.7 on 2023-11-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
